/*
 * Copyright Jason Morris 2008. All rights reserved.
 */
package net.lemnik.eodsql.mock;

import java.util.Date;
import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;

/**
 * <p>
 * </p><p>
 * Created on 13 Apr 2010
 * </p>
 *
 * @author Jason Morris
 */
public class User {

    @AutoGeneratedKeys
    private Long id;

    private String email;

    private String username;

    @ResultColumn("birth_date")
    private Date birthDate;

    private User() {
    }

    public User(
            final String email,
            final String username,
            final Date birthDate) {

        this.email = email;
        this.username = username;
        this.birthDate = birthDate;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(final Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(final String email) {
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(final String username) {
        this.username = username;
    }

}
