/*
 * AutoGeneratedKeysQuery.java
 *
 * Created on September 13, 2007, 5:39 PM
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package net.lemnik.eodsql;

import java.sql.SQLException;

/**
 *
 * @author jason
 */
public interface AutoGeneratedKeysQuery extends BaseQuery {
    @Update(
    sql="INSERT INTO keyTable (value) VALUES (?{1.value})",
    keys=GeneratedKeys.RETURNED_KEYS_COLUMNS_SPECIFIED)
    public KeyObject insertKeyColumnsSpecified(KeyObject o);
    
    @Update(
    sql="INSERT INTO keyTable (value) VALUES (?{1.value})",
    keys=GeneratedKeys.RETURNED_KEYS_DRIVER_DEFINED)
    public KeyObject insertKeyDriverDefined(KeyObject o);
    
    @Update(
    sql="INSERT INTO keyTable (value) VALUES (?{1.value})",
    keys=GeneratedKeys.RETURNED_KEYS_FIRST_COLUMN)
    public KeyObject insertKeyFirstColumn(KeyObject o);

    @Update("CREATE TABLE keyTable (ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(36) NOT NULL)")
    public void createTable();
    
    @Update("DROP TABLE keyTable")
    public void dropTable()throws SQLException;
}
