package net.lemnik.eodsql;

import java.sql.SQLException;
import java.util.UUID;

/**
 *
 * @author jason
 */
public class AutoGeneratedKeysTest extends EoDTestCase {
    private static boolean tableCreated = false;

    AutoGeneratedKeysQuery query = null;

    @Override
    protected void setUp() throws Exception {
        super.setUp();

        query = QueryTool.getQuery(getConnection(), AutoGeneratedKeysQuery.class);
        query.createTable();
        query.close();
    }

    public void testColumnsSpecified() throws Exception {
        query = QueryTool.getQuery(getConnection(), AutoGeneratedKeysQuery.class);

        KeyObject in = new KeyObject();
        in.value = UUID.randomUUID().toString();

        KeyObject out = query.insertKeyColumnsSpecified(in);
        assertNotNull("KeyObject should have been returned", out);
        assertNotNull("id should have been inserted by EoD SQL", out.id);
    }

    public void testFirstColumn() throws Exception {
        query = QueryTool.getQuery(getConnection(), AutoGeneratedKeysQuery.class);

        KeyObject in = new KeyObject();
        in.value = UUID.randomUUID().toString();

        KeyObject out = query.insertKeyFirstColumn(in);
        assertNotNull("id should have been inserted by EoD SQL", out.id);
    }

    @Override
    protected void tearDown() throws Exception {
        super.tearDown();
        
        try {
            query = QueryTool.getQuery(getConnection(), AutoGeneratedKeysQuery.class);
            query.dropTable();
        } catch(SQLException ex) {
            query.close();
            query = QueryTool.getQuery(getConnection(), AutoGeneratedKeysQuery.class);
        // ignore this, the table might not have already been created
        }

    }

}
