/*
 * KeyObject.java
 *
 * Created on September 13, 2007, 5:37 PM
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package net.lemnik.eodsql;

/**
 *
 * @author jason
 */
public class KeyObject {
    @AutoGeneratedKeys
    @ResultColumn("ID")
    public Long id;
    
    public String value;
    
    /**
     * Creates a new instance of KeyObject
     */
    public KeyObject() {
    }
    
}
